package org.school.admin.model;

// Generated Jul 12, 2015 1:22:56 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AppliedSchool generated by hbm2java
 */
@Entity
@Table(name = "applied_school")
public class AppliedSchool implements java.io.Serializable {

	private Integer id;
	private UserRegistrationInfo userRegistrationInfo;
	private ApplicantBasicDetail applicantBasicDetail;
	private School school;
	private Byte status;

	public AppliedSchool() {
	}

	public AppliedSchool(UserRegistrationInfo userRegistrationInfo,
			ApplicantBasicDetail applicantBasicDetail, School school,
			Byte status) {
		this.userRegistrationInfo = userRegistrationInfo;
		this.applicantBasicDetail = applicantBasicDetail;
		this.school = school;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public UserRegistrationInfo getUserRegistrationInfo() {
		return this.userRegistrationInfo;
	}

	public void setUserRegistrationInfo(
			UserRegistrationInfo userRegistrationInfo) {
		this.userRegistrationInfo = userRegistrationInfo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "applicant_id")
	public ApplicantBasicDetail getApplicantBasicDetail() {
		return this.applicantBasicDetail;
	}

	public void setApplicantBasicDetail(
			ApplicantBasicDetail applicantBasicDetail) {
		this.applicantBasicDetail = applicantBasicDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
