package org.school.admin.model;

// Generated Jul 12, 2015 1:22:56 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApplicantPaymentDetail generated by hbm2java
 */
@Entity
@Table(name = "applicant_payment_detail")
public class ApplicantPaymentDetail implements java.io.Serializable {

	private Integer id;
	private ApplicantBasicDetail applicantBasicDetail;
	private Double amount;
	private String paymentMode;
	private String merchantId;
	private String merchantHash;
	private Byte status;
	private String statusCode;

	public ApplicantPaymentDetail() {
	}

	public ApplicantPaymentDetail(ApplicantBasicDetail applicantBasicDetail,
			Double amount, String paymentMode, String merchantId,
			String merchantHash, Byte status, String statusCode) {
		this.applicantBasicDetail = applicantBasicDetail;
		this.amount = amount;
		this.paymentMode = paymentMode;
		this.merchantId = merchantId;
		this.merchantHash = merchantHash;
		this.status = status;
		this.statusCode = statusCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applicant_id")
	public ApplicantBasicDetail getApplicantBasicDetail() {
		return this.applicantBasicDetail;
	}

	public void setApplicantBasicDetail(
			ApplicantBasicDetail applicantBasicDetail) {
		this.applicantBasicDetail = applicantBasicDetail;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "payment_mode", length = 45)
	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "merchant_id", length = 25)
	public String getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "merchant_hash", length = 45)
	public String getMerchantHash() {
		return this.merchantHash;
	}

	public void setMerchantHash(String merchantHash) {
		this.merchantHash = merchantHash;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "status_code", length = 10)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

}
