package org.school.admin.model;

// Generated Jul 13, 2015 5:06:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApplicantParentDetail generated by hbm2java
 */
@Entity
@Table(name = "applicant_parent_detail")
public class ApplicantParentDetail implements java.io.Serializable {

	private Integer id;
	private ApplicantBasicDetail applicantBasicDetail;
	private String name;
	private String mobile;
	private String email;
	private String qualification;
	private String profession;
	private Double income;
	private Byte relationType;

	public ApplicantParentDetail() {
	}

	public ApplicantParentDetail(ApplicantBasicDetail applicantBasicDetail,
			String name, String mobile, String email, String qualification,
			String profession, Double income, String signature,
			Byte relationType) {
		this.applicantBasicDetail = applicantBasicDetail;
		this.name = name;
		this.mobile = mobile;
		this.email = email;
		this.qualification = qualification;
		this.profession = profession;
		this.income = income;
		this.relationType = relationType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applicant_id")
	public ApplicantBasicDetail getApplicantBasicDetail() {
		return this.applicantBasicDetail;
	}

	public void setApplicantBasicDetail(
			ApplicantBasicDetail applicantBasicDetail) {
		this.applicantBasicDetail = applicantBasicDetail;
	}

	@Column(name = "name", length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "mobile", length = 10)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "email", length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "qualification", length = 80)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "profession", length = 45)
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Column(name = "income", precision = 22, scale = 0)
	public Double getIncome() {
		return this.income;
	}

	public void setIncome(Double income) {
		this.income = income;
	}

	@Column(name = "relation_type")
	public Byte getRelationType() {
		return this.relationType;
	}

	public void setRelationType(Byte relationType) {
		this.relationType = relationType;
	}

}
