package org.school.admin.model;

// Generated Jul 12, 2015 1:22:56 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplicantPreSchoolDetail generated by hbm2java
 */
@Entity
@Table(name = "applicant_pre_school_detail")
public class ApplicantPreSchoolDetail implements java.io.Serializable {

	private Integer id;
	private ApplicantBasicDetail applicantBasicDetail;
	private String schoolName;
	private String fromStd;
	private String toStd;
	private Date fromDate;
	private Date toDate;
	private String grade;

	public ApplicantPreSchoolDetail() {
	}

	public ApplicantPreSchoolDetail(ApplicantBasicDetail applicantBasicDetail,
			String schoolName, String fromStd, String toStd, Date fromDate,
			Date toDate, String grade) {
		this.applicantBasicDetail = applicantBasicDetail;
		this.schoolName = schoolName;
		this.fromStd = fromStd;
		this.toStd = toStd;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.grade = grade;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "applicant_id")
	public ApplicantBasicDetail getApplicantBasicDetail() {
		return this.applicantBasicDetail;
	}

	public void setApplicantBasicDetail(
			ApplicantBasicDetail applicantBasicDetail) {
		this.applicantBasicDetail = applicantBasicDetail;
	}

	@Column(name = "school_name", length = 128)
	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	@Column(name = "from_std", length = 45)
	public String getFromStd() {
		return this.fromStd;
	}

	public void setFromStd(String fromStd) {
		this.fromStd = fromStd;
	}

	@Column(name = "to_std", length = 45)
	public String getToStd() {
		return this.toStd;
	}

	public void setToStd(String toStd) {
		this.toStd = toStd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "from_date", length = 10)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "to_date", length = 10)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Column(name = "grade", length = 25)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

}
