package org.school.admin.model;

// Generated 8 Jun, 2015 1:17:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusInfo generated by hbm2java
 */
@Entity
@Table(name = "bus_info")
public class BusInfo implements java.io.Serializable {

	private Integer id;
	private String title;
	private String busNumber;
	private String vehicleNo;
	private String busDriverName;
	private String contactNo;
	private String description;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;

	public BusInfo() {
	}

	public BusInfo(String title, String busNumber, String vehicleNo,
			String busDriverName, String contactNo, String description,
			Date lastUpdatedOn, Integer lastUpdatedBy) {
		this.title = title;
		this.busNumber = busNumber;
		this.vehicleNo = vehicleNo;
		this.busDriverName = busDriverName;
		this.contactNo = contactNo;
		this.description = description;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "bus_number", length = 10)
	public String getBusNumber() {
		return this.busNumber;
	}

	public void setBusNumber(String busNumber) {
		this.busNumber = busNumber;
	}

	@Column(name = "vehicle_no", length = 20)
	public String getVehicleNo() {
		return this.vehicleNo;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	@Column(name = "bus_driver_name", length = 100)
	public String getBusDriverName() {
		return this.busDriverName;
	}

	public void setBusDriverName(String busDriverName) {
		this.busDriverName = busDriverName;
	}

	@Column(name = "contact_no", length = 20)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
