package org.school.admin.model;

// Generated 15 Jun, 2015 4:38:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClassSection generated by hbm2java
 */
@Entity
@Table(name = "class_section")
public class ClassSection implements java.io.Serializable {

	private Integer id;
	private ClassInfo classInfo;
	private SectionType sectionType;
	private Integer lastUpdatedBy;
	private Date lastUpdatedOn;
	private Short totalSeat;
	private Short vacantSeat;
	private Date admissionFrom;
	private Date admissionTo;
	private Date admissionDeadline;

	public ClassSection() {
	}

	public ClassSection(ClassInfo classInfo, SectionType sectionType,
			Integer lastUpdatedBy, Date lastUpdatedOn, Short totalSeat,
			Short vacantSeat, Date admissionFrom, Date admissionTo,
			Date admissionDeadline) {
		this.classInfo = classInfo;
		this.sectionType = sectionType;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedOn = lastUpdatedOn;
		this.totalSeat = totalSeat;
		this.vacantSeat = vacantSeat;
		this.admissionFrom = admissionFrom;
		this.admissionTo = admissionTo;
		this.admissionDeadline = admissionDeadline;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "class_id")
	public ClassInfo getClassInfo() {
		return this.classInfo;
	}

	public void setClassInfo(ClassInfo classInfo) {
		this.classInfo = classInfo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "section_type_id")
	public SectionType getSectionType() {
		return this.sectionType;
	}

	public void setSectionType(SectionType sectionType) {
		this.sectionType = sectionType;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "total_seat")
	public Short getTotalSeat() {
		return this.totalSeat;
	}

	public void setTotalSeat(Short totalSeat) {
		this.totalSeat = totalSeat;
	}

	@Column(name = "vacant_seat")
	public Short getVacantSeat() {
		return this.vacantSeat;
	}

	public void setVacantSeat(Short vacantSeat) {
		this.vacantSeat = vacantSeat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "admission_from", length = 10)
	public Date getAdmissionFrom() {
		return this.admissionFrom;
	}

	public void setAdmissionFrom(Date admissionFrom) {
		this.admissionFrom = admissionFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "admission_to", length = 10)
	public Date getAdmissionTo() {
		return this.admissionTo;
	}

	public void setAdmissionTo(Date admissionTo) {
		this.admissionTo = admissionTo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "admission_deadline", length = 10)
	public Date getAdmissionDeadline() {
		return this.admissionDeadline;
	}

	public void setAdmissionDeadline(Date admissionDeadline) {
		this.admissionDeadline = admissionDeadline;
	}

}
