package org.school.admin.model;

// Generated Jul 12, 2015 1:22:56 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

/**
 * PostRequirement generated by hbm2java
 */
@Entity
@Table(name = "post_requirement")
public class PostRequirement implements java.io.Serializable {

	private Integer id;
	@NotNull(message="Please enter your name")
	private String name;
	private String email;
	@Pattern(regexp="[\\d]{10}||[\\d]{0}",message="Mobile number should be valid 10 digit number.")
	private String mobile;
	@NotNull(message="Please enter your requirement")
	private String requirement;

	public PostRequirement() {
	}

	public PostRequirement(String name, String email, String mobile,
			String requirement) {
		this.name = name;
		this.email = email;
		this.mobile = mobile;
		this.requirement = requirement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobile", length = 10)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "requirement", length = 65535)
	public String getRequirement() {
		return this.requirement;
	}

	public void setRequirement(String requirement) {
		this.requirement = requirement;
	}

}
