package org.school.admin.model;

// Generated Jun 11, 2015 9:07:53 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RatingCategoryType generated by hbm2java
 */
@Entity
@Table(name = "rating_category_type")
public class RatingCategoryType implements java.io.Serializable {

	private Short id;
	private String categoryName;
	private Float weightage;
	private Date lastUpdatedOn;
	private Integer lastUpdatedBy;

	public RatingCategoryType() {
	}

	public RatingCategoryType(String categoryName, Float weightage,
			Date lastUpdatedOn, Integer lastUpdatedBy) {
		this.categoryName = categoryName;
		this.weightage = weightage;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	@Column(name = "category_name", length = 200)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "weightage", precision = 9, scale = 3)
	public Float getWeightage() {
		return this.weightage;
	}

	public void setWeightage(Float weightage) {
		this.weightage = weightage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
