package org.school.admin.model;

// Generated 3 Aug, 2015 4:54:40 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SchoolPanoramicImage generated by hbm2java
 */
@Entity
@Table(name = "school_panoramic_image")
public class SchoolPanoramicImage implements java.io.Serializable {

	private Integer id;
	private School school;
	private String title;
	private String panoImage;

	public SchoolPanoramicImage() {
	}

	public SchoolPanoramicImage(School school, String title, String panoImage) {
		this.school = school;
		this.title = title;
		this.panoImage = panoImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "pano_image", length = 128)
	public String getPanoImage() {
		return this.panoImage;
	}

	public void setPanoImage(String panoImage) {
		this.panoImage = panoImage;
	}

}
