package org.school.admin.model;

// Generated Jul 9, 2015 5:40:13 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * SchoolSuggestion generated by hbm2java
 */
@Entity
@Table(name = "school_suggestion")
public class SchoolSuggestion implements java.io.Serializable {

	private Integer id;
	
	@NotEmpty(message="Name can not be empty.")
	private String personName;
	
	@NotNull(message="Mobile number can not be empty.")
	@Pattern(regexp="[\\d]{10}",message="Mobile number should be valid 10 digit number.")
	private String mobile;
	
	@NotEmpty(message="Requirment can not be empty.")
	private String requirement;
	private Integer status;

	public SchoolSuggestion() {
	}

	public SchoolSuggestion(String personName, String mobile,
			String requirement, Integer status) {
		this.personName = personName;
		this.mobile = mobile;
		this.requirement = requirement;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "person_name", length = 50)
	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	@Column(name = "mobile", length = 10)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "requirement", length = 250)
	public String getRequirement() {
		return this.requirement;
	}

	public void setRequirement(String requirement) {
		this.requirement = requirement;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
