package org.school.admin.model;

// Generated 11 Jul, 2015 4:07:33 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;

/**
 * SchoolReview generated by hbm2java
 */
@Entity
@Table(name = "school_review")
public class SchoolReview implements java.io.Serializable {

	private Integer id;
	@NotNull(message="Please enter school id")
	private School school;
	@NotNull(message="Please enter user id")
	private UserRegistrationInfo userRegistrationInfo;
	@NotNull(message="Please enter review title")
	private String title;
	@NotNull(message="Please enter the review")
	@Length(min=120,message="Minimum  120 characters required for a good review")
	private String review;
	private Date date;
	private Date time;
	private Byte status;

	public SchoolReview() {
	}

	public SchoolReview(School school) {
		this.school = school;
	}

	public SchoolReview(School school,
			UserRegistrationInfo userRegistrationInfo, String title,
			String review, Date date, Date time, Byte status) {
		this.school = school;
		this.userRegistrationInfo = userRegistrationInfo;
		this.title = title;
		this.review = review;
		this.date = date;
		this.time = time;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "school_id", nullable = false)
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userid")
	public UserRegistrationInfo getUserRegistrationInfo() {
		return this.userRegistrationInfo;
	}

	public void setUserRegistrationInfo(
			UserRegistrationInfo userRegistrationInfo) {
		this.userRegistrationInfo = userRegistrationInfo;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "review", length = 65535)
	public String getReview() {
		return this.review;
	}

	public void setReview(String review) {
		this.review = review;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
