package org.school.admin.model;

// Generated Jul 22, 2015 2:49:51 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SchoolAnalytics generated by hbm2java
 */
@Entity
@Table(name = "school_analytics")
public class SchoolAnalytics implements java.io.Serializable {

	private int id;
	private School school;
	private Integer contactClicks;

	public SchoolAnalytics() {
	}

	public SchoolAnalytics(int id, School school) {
		this.id = id;
		this.school = school;
	}

	public SchoolAnalytics(int id, School school, Integer contactClicks) {
		this.id = id;
		this.school = school;
		this.contactClicks = contactClicks;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "contact_clicks")
	public Integer getContactClicks() {
		return this.contactClicks;
	}

	public void setContactClicks(Integer contactClicks) {
		this.contactClicks = contactClicks;
	}

}
