package org.school.admin.model;

// Generated 30-May-2015 14:03:54 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransportDetails generated by hbm2java
 */
@Entity
@Table(name = "transport_details")
public class TransportDetails implements java.io.Serializable {

	private int transDetailId;
	private School school;
	private String busNumber;
	private String vehicleNumber;
	private String busDriverName;
	private String busDriverContactNumber;
	private Date lastUpdatedOn;
	private int lastUpdatedBy;

	public TransportDetails() {
	}

	public TransportDetails(int transDetailId, School school, String busNumber,
			String vehicleNumber, String busDriverName,
			String busDriverContactNumber, Date lastUpdatedOn, int lastUpdatedBy) {
		this.transDetailId = transDetailId;
		this.school = school;
		this.busNumber = busNumber;
		this.vehicleNumber = vehicleNumber;
		this.busDriverName = busDriverName;
		this.busDriverContactNumber = busDriverContactNumber;
		this.lastUpdatedOn = lastUpdatedOn;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@Column(name = "trans_detail_id", unique = true, nullable = false)
	public int getTransDetailId() {
		return this.transDetailId;
	}

	public void setTransDetailId(int transDetailId) {
		this.transDetailId = transDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "bus_number", nullable = false, length = 10)
	public String getBusNumber() {
		return this.busNumber;
	}

	public void setBusNumber(String busNumber) {
		this.busNumber = busNumber;
	}

	@Column(name = "vehicle_number", nullable = false, length = 20)
	public String getVehicleNumber() {
		return this.vehicleNumber;
	}

	public void setVehicleNumber(String vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	@Column(name = "bus_driver_name", nullable = false, length = 100)
	public String getBusDriverName() {
		return this.busDriverName;
	}

	public void setBusDriverName(String busDriverName) {
		this.busDriverName = busDriverName;
	}

	@Column(name = "bus_driver_contact_number", nullable = false, length = 100)
	public String getBusDriverContactNumber() {
		return this.busDriverContactNumber;
	}

	public void setBusDriverContactNumber(String busDriverContactNumber) {
		this.busDriverContactNumber = busDriverContactNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_on", nullable = false, length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "last_updated_by", nullable = false)
	public int getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(int lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
