package org.school.admin.model;

// Generated 21 Jul, 2015 6:41:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ViewSchool generated by hbm2java
 */
@Entity
@Table(name = "view_school")
public class ViewSchool implements java.io.Serializable {

	private int schoolId;
	private String schoolName;
	private String aliasName;
	private String localityName;
	private int cityId;
	private String cityName;
	private String schoolFullName;

	public ViewSchool() {
	}

	public ViewSchool(int schoolId, String schoolName, String aliasName,
			String localityName,int cityId, String cityName, String schoolFullName) {
		this.schoolId = schoolId;
		this.schoolName = schoolName;
		this.aliasName = aliasName;
		this.localityName = localityName;
		this.cityId = cityId;
		this.cityName = cityName;
		this.schoolFullName = schoolFullName;
	}

	@Id
	@Column(name = "school_id", unique=true, nullable = false)
	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "school_name", length = 200)
	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	@Column(name = "alias_name", length = 200)
	public String getAliasName() {
		return aliasName;
	}



	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}



	@Column(name = "locality_name", length = 200)
	public String getLocalityName() {
		return this.localityName;
	}

	public void setLocalityName(String localityName) {
		this.localityName = localityName;
	}
	@Column(name = "city_id", nullable = false)
	
	public int getCityId() {
		return cityId;
	}



	public void setCityId(int cityId) {
		this.cityId = cityId;
	}
	@Column(name = "city_name", length = 200)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "school_full_name")
	public String getSchoolFullName() {
		return this.schoolFullName;
	}

	public void setSchoolFullName(String schoolFullName) {
		this.schoolFullName = schoolFullName;
	}
}
