package org.school.admin.model;

// Generated 22 Jul, 2015 11:30:18 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ViewContact generated by hbm2java
 */
@Entity
@Table(name = "view_contact")
public class ViewContact implements java.io.Serializable {

	private int schoolId;
	private int cityId;
	private String contactName;
	private String contactNumber;
	private String contactDetail;

	public ViewContact() {
	}

	public ViewContact(int schoolId) {
		this.schoolId = schoolId;
	}

	public ViewContact(int schoolId, String contactDetail) {
		this.schoolId = schoolId;
		this.contactDetail = contactDetail;
	}

	@Id
	@Column(name = "school_id", unique=true, nullable = false)
	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}
	
	@Column(name = "city_id",nullable = false)
	
	public int getCityId() {
		return cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

	@Column(name = "contact_name", length = 200)
	public String getContactName() {
		return contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}
	@Column(name = "contact_number", length = 200)
	public String getContactNumber() {
		return contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "contact_detail", length = 223)
	public String getContactDetail() {
		return this.contactDetail;
	}

	public void setContactDetail(String contactDetail) {
		this.contactDetail = contactDetail;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewContact))
			return false;
		ViewContact castOther = (ViewContact) other;

		return (this.getSchoolId() == castOther.getSchoolId())
				&& ((this.getContactDetail() == castOther.getContactDetail()) || (this
						.getContactDetail() != null
						&& castOther.getContactDetail() != null && this
						.getContactDetail()
						.equals(castOther.getContactDetail())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSchoolId();
		result = 37
				* result
				+ (getContactDetail() == null ? 0 : this.getContactDetail()
						.hashCode());
		return result;
	}

}
